### ISSUE TITLE
swc/core issue: "Cannot find module '../index.js'"

### ISSUE THREAD

**Issue by Alex0007** [ilovepixelart/ts-migrate-mongoose#204]
Hi!

When migration imports "index" file without extension – it shows "cannot find module" error: because it is trying to require .js file instead of .ts

```ts
import { initDBConnection } from '$/db/index'; // This import is causing problem on 3.3.2

export async function up (): Promise<void> {
  //
}
```

Downgrading from `ts-migrate-mongoose@3.3.2` to `ts-migrate-mongoose@3.3.1` resolves this issue

Ref: https://github.com/swc-project/jest/issues/161

**Comment by ilovepixelart** [comment]
Hello @Alex0007, 
Interesting..., I think we can downgrade then to @swc/core 1.3.78, since upgrading to 1.3.83 where the fix was done causes jest tsnode to break

**Comment by ilovepixelart** [comment]
@Alex0007 you can update to new version 3.3.3 https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.3.3

**Comment by Alex0007** [comment]
@ilovepixelart thanks, it worked!
