### ISSUE TITLE
ts-migrate-mongoose Fails with SWC: "Unexpected token @" on Decorators

### ISSUE THREAD

**Issue by kevkeelobyte** [ilovepixelart/ts-migrate-mongoose#385]
_Firstly, thanks for this great package! It's been really helpful in managing migrations on our project, and I appreciate all the work that goes into keeping it up to date. Let me know if I can provide any more details on the below. 🚀_

**Description**

After upgrading from `ts-migrate-mongoose@3.8.3` to `3.8.4+`, running `npx migrate up` or the `Migrator` client results in an SWC syntax error related to decorators:

```
Synchronizing database with file system migrations...
  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
18 │   @Expose()
    ·   ─
 19 │   @TransformObjectId()
 20 │   _id!: string;
```

From testing, the issue may be related to `@swc-node/register` not picking up the `.swcrc` configuration correctly when executing migrations.

**To Reproduce**
1. Install `ts-migrate-mongoose@3.8.4` or later
2. Ensure you have the `.swcrc` config file at the root of your project:
```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2021",
    "baseUrl": ".",
    "paths": {
      ... ** omitted for brevity ** 
    },
    "keepClassNames": true,
    "loose": true
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

3. Run the migration command: `npx migrate up`
4. See error:
```
Synchronizing database with file system migrations...
  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
18 │   @Expose()
    ·   ─
 19 │   @TransformObjectId()
 20 │   _id!: string;
```

**Expected behavior**

- `migrate up` should successfully execute the migrations without failing due to decorator syntax errors.

- It should correctly detect the `.swcrc` configuration instead of requiring an explicit `SWCRC=true` workaround.

**Workaround**
For now, the issue can be avoided by explicitly setting the SWCRC environment variable before running migrate up:

`SWCRC=true NODE_OPTIONS="--require @swc-node/register" npx migrate up`

This forces `migrate` to use the correct SWC configuration, but ideally, `ts-migrate-mongoose` should automatically detect and apply `.swcrc` without needing manual intervention.

**Additional context**

This issue seems to be caused by a change in how `ts-migrate-mongoose` executes SWC transpilation, possibly due to an internal update in `@swc-node/register`?

If helpful, here is the installed dependency tree showing SWC versions:

├─┬ ts-migrate-mongoose@3.8.9
│ └─┬ @swc-node/register@1.10.9
│   └── @swc/core@1.7.10

This issue did not occur in `ts-migrate-mongoose@3.8.3`. Let me know if any further debugging is needed! 

- `Node.js` Version: `20.12.2`

**Comment by ilovepixelart** [comment]
I was reading some code on `@swc-node/register`, seems they went with approach of env variables
And now you have two choses:

1. If you want to use `.swcrc` as config for transpiration you need to use SWCRC=true
2. If you want to use `tsconfig.json` you need to use `SWC_NODE_PROJECT` or `TS_NODE_PROJECT` with the value of path

In second approach they read tsconfig.json, then parse `compilerOptions` and map them to `.swcrc` alternatives, so @kevkeelobyte will be helpful if you try second approach and confirm that decorators work for you during transpiration using tsconfig.json and SWC_NODE_PROJECT example here https://github.com/ilovepixelart/ts-express-swc/commit/93bc534409d05c13f78b2808af81dcb96a8c1f83

To avoid forcing people setting env variables left and right, in programmatic mode we need a way to set tscofnig path or .swcrc
But currently there is no support of that in @swc-node/register. I will think about solutions, and open an issue to address this

**Comment by ilovepixelart** [comment]
Created a proposal here: https://github.com/swc-project/swc-node/issues/902

**Comment by ilovepixelart** [comment]
Ok folks this is no longer relevant try v4, I dropped SWC entirely

**Comment by l-Nuril-l** [comment]
```
Nuril@Miyuli MINGW64 ~/Desktop/DEV
$ git clone https://github.com/ilovepixelart/ts-express-tsx
Cloning into 'ts-express-tsx'...
remote: Enumerating objects: 1649, done.
remote: Counting objects: 100% (581/581), done.
remote: Compressing objects: 100% (260/260), done.
remote: Total 1649 (delta 516), reused 352 (delta 317), pack-reused 1068 (from 3)
Receiving objects: 100% (1649/1649), 1.65 MiB | 6.11 MiB/s, done.
Resolving deltas: 100% (1081/1081), done.

Nuril@Miyuli MINGW64 ~/Desktop/DEV
$ cd ts-express-tsx/

Nuril@Miyuli MINGW64 ~/Desktop/DEV/ts-express-tsx (main)
$ npm i

added 488 packages, and audited 489 packages in 36s

95 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

Nuril@Miyuli MINGW64 ~/Desktop/DEV/ts-express-tsx (main)
$ bun x migrate
node:internal/modules/cjs/loader:1089
    throw new ERR_REQUIRE_ESM(filename, true);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Nuril\Desktop\DEV\ts-express-tsx\node_modules\tsx\dist\loader.mjs not supported.
Instead change the require of C:\Users\Nuril\Desktop\DEV\ts-express-tsx\node_modules\tsx\dist\loader.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\Nuril\Desktop\DEV\ts-express-tsx\node_modules\ts-migrate-mongoose\dist\cli.js:4:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.9.0
```

My old programmatic way
```
$ bun run migrate:down init
$ bun run --bun ./cmd/migrator.ts down init
error: Cannot find module './cjs/index.cjs' from 'undefined'

Bun v1.2.0 (Windows x64)
error: script "migrate:down" exited with code 1
```

**Comment by ilovepixelart** [comment]
```Bash
➜  ts-express-tsx git:(main) git pull
Already up to date.
➜  ts-express-tsx git:(main) npm i

added 489 packages, and audited 490 packages in 5s

96 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  ts-express-tsx git:(main) bun x migrate 
Usage: migrate [options] [command]

CLI migration tool for mongoose

Options:
  -f, --config-path <path>         path to the config file
  -d, --uri <string>               mongo connection string
  -c, --collection <string>        collection name to use for the migrations
  -a, --autosync <boolean>         automatically sync new migrations without prompt
  -m, --migrations-path <path>     path to the migration files
  -t, --template-path <path>       template file to use when creating a migration
  --mode <string>                  environment mode to use .env.[mode] file
  -h, --help                       display help for command

Commands:
  list                             list all migrations
  create <migration-name>          create a new migration file
  up [options] [migration-name]    run all migrations or a specific migration if name provided
  down [options] <migration-name>  roll back migrations down to given name
  prune                            delete extraneous migrations from migration folder or database
  help [command]                   display help for command
➜  ts-express-tsx git:(main) 
```

**Comment by l-Nuril-l** [comment]
@ilovepixelart 
I updated Node from v20.9.0 to v20.18.3, but the issue remained.
On v22.14.0, everything worked, but my project is written in Node 20.

Yes, I replaced the imports with:
`import { Migrator } from 'ts-migrate-mongoose';`
But even on version 22, when running the project, I get the error:
`Cannot find module './cjs/index.cjs' from 'undefined'`

CLI:
It doesn't recognize my migration.ts in the project root.
```
$ bun x migrate down init -f migrate.ts
Error: You need to provide the MongoDB Connection URI to persist migration status.
Use option --uri / -d to provide the URI.
```

I was able to run it with the configuration in .env
However, I ran into a new issue:
$ bun x migrate up
```
Synchronizing database with file system migrations...
Adding migration C:\Users\Nuril\Desktop\DEV\secret\src\common\migrations\local\1737039747182-init into database from file system. State is down
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:209:11)
    at defaultLoad (node:internal/modules/esm/load:107:3)
    at nextLoad (node:internal/modules/esm/hooks:748:28)
    at load (file:///C:/Users/Nuril/Desktop/DEV/secret/node_modules/tsx/dist/esm/index.mjs?1740520327601:2:1768)
    at nextLoad (node:internal/modules/esm/hooks:748:28)
    at Hooks.load (node:internal/modules/esm/hooks:385:26)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.processImmediate (node:internal/timers:491:21) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

**Comment by ilovepixelart** [comment]
I see, seems like windows related. Don't rush with transition to v4 in that case. Make sure you using 4.0.1 it has a patch for config file of you want to continue testing.

**Comment by ilovepixelart** [comment]
To address the issue I will make a quick patch for windows file url support
https://github.com/ilovepixelart/ts-migrate-mongoose/pull/390
It is released in https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v4.0.2
Try this version on windows, and let me know @l-Nuril-l

**Comment by l-Nuril-l** [comment]
@ilovepixelart Migrations and the migration.ts file work! Thanks!🎉
`Migrator.connect()` still `error: Cannot find module './cjs/index.cjs' from 'undefined'`

**Comment by ilovepixelart** [comment]
> Migrator.connect() still error: Cannot find module './cjs/index.cjs' from 'undefined'

@l-Nuril-l this one does not make sense to me, do you compile your project into one file? Before you execute migrator?
Can you reproduce it on `ts-express-tsx` repo? If so pleas provide detailed steps.
`./cjs/index.cjs` simply does not exist as entry point in ts-migrate-mongoose

**Comment by l-Nuril-l** [comment]
@ilovepixelart The problem seems to occur when running with bun

**Comment by ilovepixelart** [comment]
Ok I see, bun is not priority on my list, but if you can create a small repo example with bun, so I can just run the project and see, would be great similar to ts-express-tsc you can use any stack as long as it's reproducible.

 **ts-migrate-mongoose 4.0.2** should work with node@22 with no issues on linux/unix/windows

I will check node@20 to see if we can still support it

**Comment by l-Nuril-l** [comment]
@ilovepixelart  I got it. V4 does not work with Bun, only through tsx.
```
$ node example.js 
OK
```

```
$ bun example.js
error: Cannot find module './cjs/index.cjs' from 'undefined'
Bun v1.2.4 (Windows x64)
```

```
$ bun x tsx example.js 
OK
```

```
import { Migrator } from "ts-migrate-mongoose";

Migrator.connect({
    uri: process.env.MONGO_URI ?? 'mongodb://127.0.0.1/express',
}).then(x => console.log("OK"))
```

**Comment by ilovepixelart** [comment]
Good news, just added support for node@20
https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v4.0.3
Patch is out @l-Nuril-l let me know if it works for you, I did not check bun case in this patch but you can try just in case too

**Comment by l-Nuril-l** [comment]
@ilovepixelart Node 20 works, thanks! But Bun still doesn't.

**Comment by ilovepixelart** [comment]
```JavaScript
// example.js
import { Migrator } from 'ts-migrate-mongoose'

const main = async () => {
  // Creating migrator instance and connecting to the database
  const migrator = await Migrator.connect({
    uri: process.env.MIGRATE_MONGO_URI ?? 'mongodb://localhost:27017/example',
  })

  // You can do something else here, but this is as simple test

  // Closing the connection with the database
  await migrator.close()
  console.log('OK')
}

main()
```

Now should work in patch 4.0.4 https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v4.0.4
I checked with bun and deno:

```Bash
➜  test git:(main) ✗ bun example.js
Skipped tsx
OK
➜  test git:(main) ✗ deno --allow-env --allow-sys --allow-write --allow-read --allow-net example.js
Skipped tsx
OK
```

**Comment by l-Nuril-l** [comment]
@ilovepixelart 
I successfully migrated my project to V4.
I also completely removed the wrapper for the programmatic approach since the built-in tools now properly recognize my aliases.
Huge thanks for the fixes! 🚀

**Comment by ilovepixelart** [comment]
In [v4.0.6](https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v4.0.6) ESM is now fully supported, give it a try.
